### ISSUE TITLE
Minor UI fixes in v0.7.0

### ISSUE THREAD

**Issue by marcua** [Locu/chronology#307]
Having played with the new Jia for an hour, I love it!  Here are a few small fixies:
- The download button doesn't appear to do anything
- The gear/download buttons should have the nice tooltips that the toolbar does
- In edit mode, we should take up way more of the width of the screen---nearly 100% in my opinion

This is such a sweet tool!

**Comment by derek-schultz** [comment]
Points 1 and 3 have been closed separately. Opening new issue for point 2.
