### ISSUE TITLE
Mismatch on kronos port with documentation

### ISSUE THREAD

**Issue by joshblum** [Locu/chronology#382]
The kronos README uses port `8151` but the docker command runs `kronosd` on port `8150`. Which port is supposed to be the default?

**Comment by marcua** [comment]
I think it's OK that the kronos README stays at 8151.  But perhaps the
Kronos docker should work on port 80, like Metis and Jia, and then we have
in the documentation how to map it to a different port on the host machine.

**Comment by joshblum** [comment]
gotcha sounds good :)
